Fix package removal logic in nene script

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -252,16 +252,16 @@ export DRY_RUN_PROMPT="[DRY-RUN MODE]"; shift;;
 if dpkg -s "$pkg" >/dev/null 2>&1; then
    # echo "Paket bisa dihapus"
 if check_connection; then echo; else offline_status; exit $?; fi
-    echo
+    true
 else
     sed -i "/^$pkg$/d" "$PKG_SHARE_NENE/pkg-installed"
-    echo "Cannot remove this packages"
+    # succesfully removed
     exit 2
 fi
     read -r __url__ __endpoint__ < <(curl -s "${NEPI}" | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io' | sort -ur | awk '{endpoint=gensub(".*/", "", "g", $0)
     full="https://luisadha.github.io/" endpoint
     print full "\t" endpoint                    }' | fzf -0 --with-nth=2 --prompt="$REMOVE: " --delimiter=$'\t' --bind="alt-r:execute(dpkg -r \"\$pkg\")+abort" -q ${pkg:-$__url__} );
-         set +vx
+         [ $? -eq 0 ] && nene -r "$pkg"; echo "Cannot remove this packages" || which $pkg
          exit $?;
          ;;
     -i*|--install) [ -z "$2" ] && echo "Argument required for ${2:-"--install"} <package>" && exit 1
