Update nene

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -104,9 +104,14 @@ done
 
 #+ Advanced argument
 #1
-  if [[ -z "$SELECT_ARG" ]] && [[ -z "$S_ARG" ]]; then
-      echo -e "Invalid option, you mean \`$arg=' ?";
-     exit 3
+  if [[ -z "$SELECT_ARG" && -z "$S_ARG" ]]; then
+    if [[ "$arg" == *=* ]]; then
+      parse="$arg"
+    else
+      parse="${arg}="
+    fi
+  echo -e "Invalid option, you mean \`$parse\value' ?"
+  exit 3
   elif [[ "$SELECT_ARG" ]] || [[ "$S_ARG" ]] || [[ "$_S_ARG" ]]; then
   mode="select"
     if [ "$SELECT_ARG" ]; then
