Update nene

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -28,22 +28,43 @@ Usage :
   -h    --help          Print this message.
 EOF
       ;;
-    -m=*|--mode=*)
+    --mode=*)
       MODE_ARG="${arg#--mode=}"
-         M_ARG="${arg#-m=}"
       mode="online"
       ;;
-    -s=*|--select=*)
+    -m=*)
+      M_ARG="${arg#-m=}"
+      mode="online"
+      ;;
+    --select=*)
       SELECT_ARG="${arg#--select=}"
-           S_ARG="${arg#-s=}"
+      mode="select"
+      ;;
+    -s=*)
+      S_ARG="${arg#-s=}"
       mode="select"
       ;;
   esac
 done
 
-if [[ "$MODE_ARG" == "online" ]] || [[ "$M_ARG" == "online" ]]; then
-mode="online"
-read __url__ < <(
+#+ Advanced argument
+#1
+  if [[ "$SELECT_ARG" ]] || [[ "$S_ARG" ]]; then
+  mode="select"
+    if [ "$SELECT_ARG" ]; then
+    SPARAM="$SELECT_ARG"
+    elif [ "$S_ARG" ]; then
+    SPARAM="$S_ARG"
+    else
+    SPARAM=" "
+    exit 1
+    fi 
+      read __url__ __endpoint__ < <( curl -s https://not-echo-not-true.carrd.co 2>/dev/null | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' |  fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -1 -0 -q "${SPARAM:-}");  [ -z "$SPARAM" ] && echo -e "\nCaught ^C" || echo -e "Executing.. $__endpoint__"; . <(curl -sL $__url__ 2>/dev/null)
+  fi 
+#2
+  if [[ "$MODE_ARG" == "online" ]] || [[ "$M_ARG" == "online" ]]; then
+mode="online";
+  read __url__ < <(
   curl -s https://not-echo-not-true.carrd.co |
     html2text |
     grep -oP '(?<=\])\(\K[^)]+' |
@@ -51,16 +72,15 @@ read __url__ < <(
     grep -E 'github\.com|github\.io|luisadha\.my\.id' |
     sort -ur |
     awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' |
-    fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t')
-
-[ -z "$__url__" ] && echo -e "\nCaught ^" || . <(curl -sL $__url__)
-elif [[ "$MODE_ARG" == "default" ]]; then
+    fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t');  [ -z "$__url__" ] && echo -e "\nCaught ^" || . <(curl -sL $__url__)
+  elif [[ "$MODE_ARG" == "default" ]] || [[ "$M_ARG" == "default" ]]; then
 mode="default"
-elif [[ -n "$MODE_ARG" ]]; then
-  echo -e "Invalid value, you mean \`--mode=online' ?"
-  exit 3
-fi
+  elif [[ -n "$MODE_ARG" ]] && [[ -n "$M_ARG" ]]; then 
+    echo -e "Invalid value, you mean \`$MODE_ARG=online' ?";
+    exit 3
+  fi
 
+# general argument
 if [[ "$mode" == "default" || "$mode" == "offline" ]]; then
   exec python3 "${__DIR__}/not-echo-not-true.py"
 elif [[ "$mode" == "url" ]]; then
@@ -72,20 +92,10 @@ elif [[ "$mode" == "url" ]]; then
   sort -ur | fzf --prompt="Choose URL: " |
   xargs -r termux-open-url);
 elif [[ "$mode" == "select" ]]; then
-  read __url__ __endpoint__ < <(
-  curl -s https://not-echo-not-true.carrd.co 2>/dev/null |
-    html2text |
-    grep -oP '(?<=\])\(\K[^)]+' |
-    grep '^https\?://' |
-    grep -E 'github\.com|github\.io|luisadha\.my\.id' |
-    sort -ur |
-    awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' |
-    fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -q "${SELECT_ARG:-$S_ARG}" -1 -0) || { echo "gagal"; } 
-  echo -e "Executing.. $__endpoint__"
-  . <(curl -sL $__url__ 2>/dev/null)
+  : || exit 0
 elif [[ "$mode" == "help" ]]; then
   : || exit 0
 else
-  echo -e "Invalid option."
+  echo -e "Invalid option or request vaule, Please see --help"
   exit 1
 fi
