Update nene

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -132,7 +132,11 @@ fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -1 -0 -q "${SPARA
 [ -z "$SPARAM" ] && echo -e "\nCaught ^C" || echo -e "Executing.. $__endpoint__"; . <(curl -sL $__url__ 2>/dev/null)
   fi 
 #2
-  if [[ "$MODE_ARG" == "online" ]] || [[ "$M_ARG" == "online" ]]; then
+  if [[ -n "$MODE_ARG" ]] && [[ -n "$M_ARG" ]]; then 
+    echo -e "❌ Invalid value, you mean \`$MODE_ARG=online' ?";
+    exit 3
+  fi
+  elif [[ "$MODE_ARG" == "online" ]] || [[ "$M_ARG" == "online" ]]; then
 mode="online";
   read __url__ < <(curl -s https://not-echo-not-true.carrd.co |
     html2text |
@@ -144,9 +148,6 @@ mode="online";
     fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t');  [ -z "$__url__" ] && echo -e "\nCaught ^" || . <(curl -sL $__url__)
   elif [[ "$MODE_ARG" == "default" ]] || [[ "$M_ARG" == "default" ]]; then
 mode="default"
-  elif [[ -n "$MODE_ARG" ]] && [[ -n "$M_ARG" ]]; then 
-    echo -e "❌ Invalid value, you mean \`$MODE_ARG=online' ?";
-    exit 3
   fi
 
 # general argument
