Update nene

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -5,7 +5,7 @@
 
 # shellcheck disable=SC1090
 PACKAGE="nene"
-VERSION="1.5.54b"
+VERSION="1.5.55b"
 NEPI="luisadha.my.id" # formerly not-echo-not-true.carrd.co
 V_FLAGS='--version' # GLOBAL FLAGS
 E_MATCH='--exact' # FZF FLAGS
@@ -51,6 +51,19 @@ local pkg="$1"
     curl -s https://api.github.com/repos/luisadha/${pkg}/releases \
   | jq -r 'max_by(.published_at).published_at[:10]'
    return 0
+}
+suggest() {
+read -r __url__ __endpoint__ < <(
+  curl -s https://not-echo-not-true.carrd.co 2>/dev/null |
+  html2text |
+  grep -oP '(?<=\])\(\K[^)]+' |
+  grep '^https\?://' |
+  grep -E 'github\.com|github\.io|luisadha\.my\.id' |
+  sort -ur |
+  awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' |
+  fzf --exact --with-nth=2 --prompt="Choose to Remove (script): " --delimiter='\t' -1 -0
+)
+echo "$__endpoint__"
 }
 online_apps() {
     read -r __url__ < <(curl -s https://not-echo-not-true.carrd.co |
@@ -371,7 +384,7 @@ keyword="$2"
   exit 0
   ;;
     *)
-      echo "Error: Unknown options"
+     [ "$1" == "-R" || "$1" == "--uninstall" ] && suggest || echo "Error: Unknown options"
       exit 1;
     ;;
   esac
