Update nene

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -151,28 +151,26 @@ if [[ "$mode" == "online" ]]; then
     sort -ur |
     awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' |
     fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t');  [ -z "$__url__" ] && echo -e "\nCaught ^" || . <(curl -sL $__url__)
- 
+   exit 0
 elif [[ "$mode" == "default" || "$mode" == "offline" ]]; then
-  exec python3 "${__DIR__}/not-echo-not-true.py"
+    exec python3 "${__DIR__}/not-echo-not-true.py"
+    exit 0
 elif [[ "$mode" == "url" ]]; then
-      read __url__ < <(curl -s https://not-echo-not-true.carrd.co |
-  html2text | grep -oP '(?<=\])\(\K[^)]+' |
-  grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' |   sort -ur | fzf --prompt="Indexing URL: " |
-  xargs -r termux-open-url);
+    read __url__ < <(curl -s https://not-echo-not-true.carrd.co | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | fzf --prompt="Indexing URL: " | xargs -r termux-open-url);
+    exit 0
 elif [[ "$mode" == "select" ]]; then
-      if [ "$SELECT_ARG" ]; then
-      SPARAM="$SELECT_ARG"
-      elif [ "$S_ARG" ]; then
-      SPARAM="$S_ARG"
-      else
-      SPARAM="$_S_ARG"
-      fi 
-      read __url__ __endpoint__ < <(curl -s https://not-echo-not-true.carrd.co 2>/dev/null | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' | fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -1 -0 -q "${SPARAM:-}");
-    [ -z "$SPARAM" ] && echo -e "\nCaught ^C" || echo -e "Executing.. $__endpoint__"; . <(curl -sL $__url__ 2>/dev/null)
- 
+        if [ "$SELECT_ARG" ]; then
+          SPARAM="$SELECT_ARG"
+        elif [ "$S_ARG" ]; then
+          SPARAM="$S_ARG"
+        else
+          SPARAM="$_S_ARG"
+        fi 
+    read __url__ __endpoint__ < <(curl -s https://not-echo-not-true.carrd.co 2>/dev/null | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' | fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -1 -0 -q "${SPARAM:-}"); [ -z "$SPARAM" ] && echo -e "\nCaught ^C" || echo -e "Executing.. $__endpoint__"; . <(curl -sL $__url__ 2>/dev/null)
+    exit 0
 elif [[ "$mode" == "help" ]]; then
-  : || exit 0
+    exit 0
 else
-  echo -e "Invalid option or request vaule, Please see --help"
-  exit 1
+    echo -e "Invalid option or request vaule, Please see --help"
+    exit 1
 fi
