Added -Si options

diff --git a/bin/nene b/bin/nene
--- a/bin/nene
+++ b/bin/nene
@@ -219,11 +219,38 @@ read -r __url__ __endpoint__ < <(curl -s https://not-echo-not-true.carrd.co 2>/d
       read -r url repo < <(curl -s https://not-echo-not-true.carrd.co 2>/dev/null | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' | fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -q "${keyword:-}" -1 -0)
         echo "$url $repo"
       if [ -n "$keyword" ]; then
-        curl -s "https://api.github.com/repos/luisadha/${repo}/contents/bin"
-       # [[ $? -eq 0 ]] && pushd "$PREFIX" && wget -O ${repo} ${url} && chmod +x ${repo} && popd
+        status=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/luisadha/${repo}/contents/bin")
+        if [ "$status" = "200" ]; then
+          echo "fallback=true"
+        else
+          echo "fallback=false"
+        fi
+        exit 0;
       else
         echo "❌ Tidak ditemukan repo dari $url"
         exit 1;
+      fi
+    ;;
+    -Si|-iS)
+        keyword="$2";
+        if [ -z "$keyword" ]; then
+          echo "Error: option -$arg request an argument"; exit 2;
+        fi
+      read -r url repo < <(curl -s https://not-echo-not-true.carrd.co 2>/dev/null | html2text | grep -oP '(?<=\])\(\K[^)]+' | grep '^https\?://' | grep -E 'github\.com|github\.io|luisadha\.my\.id' | sort -ur | awk '{print $0 "\t" gensub(".*/", "", "g", $0)}' | fzf --with-nth=2 --prompt="Choose (script): " --delimiter='\t' -q "${keyword:-}" -1 -0)
+        echo "$url $repo"
+      if [ -n "$keyword" ]; then
+        status=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/luisadha/${repo}/contents/bin")
+        if [ "$status" = "200" ]; then
+            echo "fallback=true"
+            [[ $? -eq 0 ]] && echo "Installing.." && pushd "$PREFIX" && wget -O ${repo} ${url} && chmod +x ${repo} && popd
+        else
+            echo "fallback=false"
+            echo "❌ Can't find package from $url, install failed!"
+            exit 1;
+        fi
+            exit 0;
+        else
+         echo "Error";
       fi
     ;;
     *)
